### ISSUE TITLE
GIF URLs ending in &size=1024

### ISSUE THREAD

**Issue by Jake0720** [n303p4/kitsuchan-2#6]
https://github.com/n303p4/kitsuchan-2/blob/f925fca6b51f1cbb87d21841f4300c0ba67a03f7/cogs/core/avatar.py#L21

Wondering if you could remove the "&size=1024" from the url when using the avatar command on nitro users with a gif. It doesn't allow the gif embed to animate with that on the end, so if you want to see the gif you have to visit the link.

**Comment by n303p4** [comment]
Yeah, I can do this.

**Comment by n303p4** [comment]
Resolved in 911f347.
